name: Scraper

on:
  schedule:
    - cron: '0 */4 * * *'

  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
          playwright install

      - name: Run scraper
        run: |
          python main.py